; COMMUNITY_SUBMITTED = 1
; This INI was submitted by a user via UWUVCI.
; UWUVCI_Version = 3.201.2
; Submitted_UTC = 2026-06-28 17:24 UTC
; Please verify before treating as official.

;DOOM 64

[RomOption]
Rumble = 0
RetraceByVsync = 1
BackupType = 0
BackupSize = 512
TrueBoot = 1
ExpansionPak = 0
MemPak = 1
CounterFactor = 1

[Input]
StickModify = 2